[main]
runtime_rootpath = "runtime/"


[server]
run_mode = "debug"
host = "localhost"
port = 8000
read_timeout = 60
write_timeout = 60

[logger]
save_path = "logs/"
save_name = "log"
file_ext = "log"
time_format = 20060102